# Generated by Django 4.0.1 on 2022-03-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminssion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=191)),
                ('email', models.EmailField(blank=True, max_length=191)),
                ('phone', models.CharField(blank=True, max_length=191)),
                ('father_name', models.CharField(blank=True, max_length=191)),
                ('mother_name', models.CharField(blank=True, max_length=191)),
                ('image', models.ImageField(upload_to='profile/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
